### PR TITLE
Fix compilation for ArduinoCore-mbed based cores

### LINKED ISSUE #12: Compilation fails on all Arduino boards using ArduinoCore-mbed
Includes Nano 33 BLE, Raspberry Pi Pico, Portenta H7 and more.

This is because:
1. The `ArduinoTimer` class defined in this library directly conflicts with `ArduinoTimer` from the core. (Should have used a unique name)

https://github.com/Megunolink/MLP/blob/dec47782f92a470376f8a28b1fc6fcc85e96f0d6/src/ArduinoTimer.h#L15-L19

vs 
https://github.com/arduino/ArduinoCore-mbed/blob/80310080316bee7d0ff5c72392554dbaa29a7f11/cores/arduino/timer.h#L13-L15

2. The `Formatting.h` file doing a `#include "Print.h"` to get `Print` and `Printable` class declarations is wrong because in ArduinoCore-mbed, when including this header directly, these classes are scoped in the `arduino` namespace, but the `Formatting.h` doesn't have `using namespace arduino;` in it. (Should have just used `#include <Arduino.h>`)
https://github.com/Megunolink/MLP/blob/dec47782f92a470376f8a28b1fc6fcc85e96f0d6/src/Formatting.h#L6

This results in a wall of compiler errors for the user, such as [happened here](https://community.platformio.org/t/i-get-errors-after-installing-megunolink-library/33642?u=maxgerhardt).

```
In file included from lib\MLP\src\Formatting.cpp:6:
lib\MLP\src\Formatting.h:17:1: error: expected class-name before '{' token
 {
 ^
lib\MLP\src\Formatting.h:36:1: error: expected class-name before '{' token
 {
 ^
*** [.pio\build\nano33ble\libd56\MLP\Formatting.cpp.o] Error 1
lib\MLP\src\ArduinoTimer.cpp:3:1: error: reference to 'ArduinoTimer' is ambiguous
 ArduinoTimer::ArduinoTimer()
 ^~~~~~~~~~~~
In file included from C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/Arduino.h:103,
                 from lib\MLP\src\ArduinoTimer.h:15,
                 from lib\MLP\src\ArduinoTimer.cpp:1:
C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/timer.h:15:9: note: candidates are: 'class arduino::ArduinoTimer'
   class ArduinoTimer {
         ^~~~~~~~~~~~
In file included from lib\MLP\src\ArduinoTimer.cpp:1:
lib\MLP\src\ArduinoTimer.h:17:7: note:                 'class ArduinoTimer'
 class ArduinoTimer
       ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp:8:6: error: reference to 'ArduinoTimer' is ambiguous
 bool ArduinoTimer::TimePassed_Milliseconds(uint32_t uPeriod, bool bAutoReset)
      ^~~~~~~~~~~~
In file included from C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/Arduino.h:103,
                 from lib\MLP\src\ArduinoTimer.h:15,
                 from lib\MLP\src\ArduinoTimer.cpp:1:
C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/timer.h:15:9: note: candidates are: 'class arduino::ArduinoTimer'
   class ArduinoTimer {
         ^~~~~~~~~~~~
In file included from lib\MLP\src\ArduinoTimer.cpp:1:
lib\MLP\src\ArduinoTimer.h:17:7: note:                 'class ArduinoTimer'
 class ArduinoTimer
       ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp: In function 'bool TimePassed_Milliseconds(uint32_t, bool)':
lib\MLP\src\ArduinoTimer.cpp:13:14: error: 'm_uStartTime' was not declared in this scope
   if (uNow - m_uStartTime >= uPeriod)
              ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp: At global scope:
lib\MLP\src\ArduinoTimer.cpp:23:6: error: reference to 'ArduinoTimer' is ambiguous
 bool ArduinoTimer::TimePassed_Seconds(uint16_t uPeriod, bool bAutoReset)
      ^~~~~~~~~~~~
In file included from C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/Arduino.h:103,
                 from lib\MLP\src\ArduinoTimer.h:15,
                 from lib\MLP\src\ArduinoTimer.cpp:1:
C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/timer.h:15:9: note: candidates are: 'class arduino::ArduinoTimer'
   class ArduinoTimer {
         ^~~~~~~~~~~~
In file included from lib\MLP\src\ArduinoTimer.cpp:1:
lib\MLP\src\ArduinoTimer.h:17:7: note:                 'class ArduinoTimer'
 class ArduinoTimer
       ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp: In function 'bool TimePassed_Seconds(uint16_t, bool)':
lib\MLP\src\ArduinoTimer.cpp:28:15: error: 'm_uStartTime' was not declared in this scope
   if ((uNow - m_uStartTime)/1000 >= uPeriod)
               ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp: At global scope:
lib\MLP\src\ArduinoTimer.cpp:38:6: error: reference to 'ArduinoTimer' is ambiguous
 bool ArduinoTimer::TimePassed_Minutes(uint16_t uPeriod, bool bAutoReset)
      ^~~~~~~~~~~~
In file included from C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/Arduino.h:103,
                 from lib\MLP\src\ArduinoTimer.h:15,
                 from lib\MLP\src\ArduinoTimer.cpp:1:
C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/timer.h:15:9: note: candidates are: 'class arduino::ArduinoTimer'
   class ArduinoTimer {
         ^~~~~~~~~~~~
In file included from lib\MLP\src\ArduinoTimer.cpp:1:
lib\MLP\src\ArduinoTimer.h:17:7: note:                 'class ArduinoTimer'
 class ArduinoTimer
       ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp: In function 'bool TimePassed_Minutes(uint16_t, bool)':
lib\MLP\src\ArduinoTimer.cpp:44:19: error: 'm_uStartTime' was not declared in this scope
   uDelta = uNow - m_uStartTime;
                   ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp: At global scope:
lib\MLP\src\ArduinoTimer.cpp:56:6: error: reference to 'ArduinoTimer' is ambiguous
 bool ArduinoTimer::TimePassed_Hours( uint16_t uPeriod, bool bAutoReset /*= true*/ )
      ^~~~~~~~~~~~
In file included from C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/Arduino.h:103,
                 from lib\MLP\src\ArduinoTimer.h:15,
                 from lib\MLP\src\ArduinoTimer.cpp:1:
C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/timer.h:15:9: note: candidates are: 'class arduino::ArduinoTimer'
   class ArduinoTimer {
         ^~~~~~~~~~~~
In file included from lib\MLP\src\ArduinoTimer.cpp:1:
lib\MLP\src\ArduinoTimer.h:17:7: note:                 'class ArduinoTimer'
 class ArduinoTimer
       ^~~~~~~~~~~~
lib\MLP\src\ArduinoTimer.cpp: In function 'bool TimePassed_Hours(uint16_t, bool)':
lib\MLP\src\ArduinoTimer.cpp:62:19: error: 'm_uStartTime' was not declared in this scope
   uDelta = uNow - m_uStartTime;
                   ^~~~~~~~~~~~
*** [.pio\build\nano33ble\libd56\MLP\ArduinoTimer.cpp.o] Error 1
In file included from lib\MLP\src\UdpParser.cpp:1:
lib\MLP\src\UdpParser.h:27:5: error: reference to 'ArduinoTimer' is ambiguous
     ArduinoTimer m_tmrPacketCheck;
     ^~~~~~~~~~~~
In file included from C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/Arduino.h:103,
                 from lib\MLP\src\CommandDispatcherBase.h:2,
                 from lib\MLP\src\UdpParser.h:3,
                 from lib\MLP\src\UdpParser.cpp:1:
C:\Users\Max\.platformio\packages\framework-arduino-mbed@3.1.1\cores\arduino/timer.h:15:9: note: candidates are: 'class arduino::ArduinoTimer'
   class ArduinoTimer {
         ^~~~~~~~~~~~
In file included from lib\MLP\src\UdpParser.h:5,
                 from lib\MLP\src\UdpParser.cpp:1:
lib\MLP\src\ArduinoTimer.h:17:7: note:                 'class ArduinoTimer'
 class ArduinoTimer
       ^~~~~~~~~~~~
lib\MLP\src\UdpParser.cpp: In member function 'void MLP::UdpParser::Process()':
lib\MLP\src\UdpParser.cpp:14:7: error: 'm_tmrPacketCheck' was not declared in this scope
   if (m_tmrPacketCheck.TimePassed_Milliseconds(PacketCheckInterval))
       ^~~~~~~~~~~~~~~~
*** [.pio\build\nano33ble\libd56\MLP\UdpParser.cpp.o] Error 1
======================================================================== [FAILED] Took 7.76 seconds ========================================================================
```

### PR DESCRIPTION
**Pull request by maxgerhardt**
Fix #12 by 
1. renaming `ArduinoTimer` class and files to `MegunoArduinoTimer`
2. `#include <Arduino.h>` instead of `#include "Print.h"` in `Formatting.h`

### CODE REVIEW

**Comment by PaulMartinsen** [comment]
Thanks for spotting this problem and taking the time to create the PR. Much appreciated. 

I'm happy with solution for second problem. But not keen on breaking backwards compatibility to get `ArduinoTimer.cpp` to compile when only mbed is affected. Do you know if `#include <Arduino.h>` is bringing the mbed implementation of `ArduinoTimer` into the global scope? 

I'd consider these alternatives first, if you haven't already:
* can we disambiguate our definitions in global scope using something like `::ArduinoTimer::ArduinoTimer()`. I don't strike this problem often enough to know if that works without trying it, which i don't have time to do right now. 
* put our `ArduinoTimer` into a MegunoLink namespace for mbed only. 
* cleverly put our `ArduinoTimer` into a MegunoLink namespace when building `ArduinoTimer.cpp` then pop it into the global namespace with a `using namespace MegunoLink` inside our `ArduinoTimer.h` is included by anything else. That preserves compatibility. Might be a problem if the `mbed` and `MegunoLink` versions of `ArduinoTimer.h` are used in the same place, but that seems a extreme edge case to me. 

What do you think?

**Comment by maxgerhardt** [comment]
>cleverly put our ArduinoTimer into a MegunoLink namespace when building ArduinoTimer.cpp then pop it into the global namespace with a using namespace MegunoLink inside our ArduinoTimer.h is included by anything else. 

You'd still have the fundamental problem that if `#include <ArduinoTimer.h>` is encountered, you get whatever header happens to be first found in the `-I` search paths. I think I remember PlatformIO and the Arduino IDE differing here, one putting the core includes last, the other putting them first.. Which would break instantly.

**Comment by maxgerhardt** [comment]
Could work. Would need to check it out and regression test compilation (best to do with CI :) )

**Comment by PaulMartinsen** [comment]
I've done some exploration in the `develop` branch. It looks like `::` can disambiguate our `ArduinoTimer` in the global scope from the mbed version in the `arduino` namespace. Or at least it builds for me with a Pico Pi target. 

I need to do a bit more testing though. It looks like this may be working because the `arduino` namespace remains attached to the mbed `ArduinoTimer` despite the `using namespace arduino;` in their `Arduino.h` file. I didn't realize that happened, and/or if it is relying on a particular version of C++. If it checks out, this could be a nice solution that maintains backwards compatibility.

**Comment by maxgerhardt** [comment]
I see CI has been implemented and fixes like https://github.com/Megunolink/MLP/commit/7027e802361c5a169ce3809d2b6bb8677264e84e on top of more were added to fix compilability -- thus closing.

**Pull request closed without merging**
